export const friendConstants = {
  GET_FRIEND_REQUESTS_SUCCESS: "GET_FRIEND_REQUESTS_SUCCESS",
  GET_FRIEND_REQUESTS_FAILURE: "GET_FRIEND_REQUESTS_FAILURE",

  GET_FRIENDS_REQUEST: "GET_FRIENDS_REQUEST",
  GET_FRIENDS_SUCCESS: "GET_FRIENDS_SUCCESS",
  GET_FRIENDS_FAILURE: "GET_FRIENDS_FAILURE",
};
