export const sayingConstants = {
  GET_ALL_SAYINGS_SUCCESS: "GET_ALL_SAYINGS_SUCCESS",
  GET_ALL_SAYINGS_FAILURE: "GET_ALL_SAYINGS_FAILURE",

  SAVE_RECORDING_REQUEST: "SAVE_RECORDING_REQUEST",
  SAVE_RECORDING_SUCCESS: "SAVE_RECORDING_SUCCESS",
  SAVE_RECORDING_FAILURE: "SAVE_RECORDING_FAILURE",

  DELETE_SAYING_REQUEST: "DELETE_SAYING_REQUEST",
  DELETE_SAYING_SUCCESS: "DELETE_SAYING_SUCCESS",
  DELETE_SAYING_FAILURE: "DELETE_SAYING_FAILURE",

  GET_SAYINGS_REQUEST: "GET_SAYINGS_REQUEST",
  GET_SAYINGS_SUCCESS: "GET_SAYINGS_SUCCESS",
  GET_SAYINGS_FAILURE: "GET_SAYINGS_FAILURE",

  GET_SAYING_REQUEST: "GET_SAYING_REQUEST",
  GET_SAYING_SUCCESS: "GET_SAYING_SUCCESS",
  GET_SAYING_FAILURE: "GET_SAYING_FAILURE",

  ADD_SAYING_SUCCESS: "ADD_SAYING_SUCCESS",
  ADD_SAYING_FAILURE: "ADD_SAYING_FAILURE",
};
