export const setConstants = {
  ADD_NEW_SET_SUCCESS: "ADD_NEW_SET_SUCCESS",
  ADD_NEW_SET_FAILURE: "ADD_NEW_SET_FAILURE",
  ADD_NEW_SET_REQUEST: "ADD_NEW_SET_REQUEST",

  GET_SETS_REQUEST: "GET_SETS_REQUEST",
  GET_SETS_SUCCESS: "GET_SETS_SUCCESS",
  GET_SETS_FAILURE: "GET_SETS_FAILURE",
};
